"""Fixed Markdown labels; JSON schema keys and sentinels remain stable."""

LANGUAGE_LABELS = {'en': ['Meeting Summary',
        'Topics',
        'Decisions',
        'Action Items',
        'Risks',
        'Open Questions',
        'None captured.',
        'Untitled',
        'Profile',
        'Model',
        'Generated',
        'Owner',
        'Due',
        'Timestamp',
        'Timestamps'],
 'es': ['Resumen de la reunión',
        'Temas',
        'Decisiones',
        'Tareas',
        'Riesgos',
        'Preguntas abiertas',
        'No se registraron elementos.',
        'Sin título',
        'Perfil',
        'Modelo',
        'Generado',
        'Responsable',
        'Fecha límite',
        'Marca de tiempo',
        'Marcas de tiempo'],
 'fr': ['Résumé de la réunion',
        'Sujets',
        'Décisions',
        'Actions',
        'Risques',
        'Questions ouvertes',
        'Aucun élément relevé.',
        'Sans titre',
        'Profil',
        'Modèle',
        'Généré',
        'Responsable',
        'Échéance',
        'Horodatage',
        'Horodatages'],
 'de': ['Besprechungszusammenfassung',
        'Themen',
        'Entscheidungen',
        'Aufgaben',
        'Risiken',
        'Offene Fragen',
        'Keine Einträge erfasst.',
        'Ohne Titel',
        'Profil',
        'Modell',
        'Erstellt',
        'Verantwortlich',
        'Fällig',
        'Zeitstempel',
        'Zeitstempel'],
 'zh': ['会议摘要',
        '主题',
        '决定',
        '待办事项',
        '风险',
        '待解决问题',
        '未记录任何内容。',
        '无标题',
        '模式',
        '模型',
        '生成时间',
        '负责人',
        '截止日期',
        '时间戳',
        '时间戳'],
 'ja': ['会議の要約',
        '議題',
        '決定事項',
        '作業項目',
        'リスク',
        '未解決の質問',
        '記録された項目はありません。',
        '無題',
        '形式',
        'モデル',
        '生成日時',
        '担当者',
        '期限',
        '時刻',
        '時刻'],
 'it': ['Riepilogo della riunione',
        'Argomenti',
        'Decisioni',
        'Attività',
        'Rischi',
        'Domande aperte',
        'Nessun elemento registrato.',
        'Senza titolo',
        'Profilo',
        'Modello',
        'Generato',
        'Responsabile',
        'Scadenza',
        'Orario',
        'Orari'],
 'pa': ['ਮੀਟਿੰਗ ਦਾ ਸਾਰ',
        'ਵਿਸ਼ੇ',
        'ਫ਼ੈਸਲੇ',
        'ਕੰਮ',
        'ਜੋਖਮ',
        'ਖੁੱਲ੍ਹੇ ਸਵਾਲ',
        'ਕੋਈ ਜਾਣਕਾਰੀ ਦਰਜ ਨਹੀਂ ਕੀਤੀ ਗਈ।',
        'ਬਿਨਾਂ ਸਿਰਲੇਖ',
        'ਪ੍ਰੋਫਾਈਲ',
        'ਮਾਡਲ',
        'ਤਿਆਰ ਕੀਤਾ',
        'ਜ਼ਿੰਮੇਵਾਰ',
        'ਮਿਆਦ',
        'ਸਮਾਂ',
        'ਸਮੇਂ'],
 'hi': ['बैठक का सारांश',
        'विषय',
        'निर्णय',
        'कार्य',
        'जोखिम',
        'खुले प्रश्न',
        'कोई जानकारी दर्ज नहीं की गई।',
        'शीर्षक रहित',
        'प्रोफ़ाइल',
        'मॉडल',
        'तैयार किया गया',
        'जिम्मेदार',
        'समय सीमा',
        'समय',
        'समय'],
 'ko': ['회의 요약',
        '주제',
        '결정 사항',
        '작업 항목',
        '위험',
        '미해결 질문',
        '기록된 항목이 없습니다.',
        '제목 없음',
        '프로필',
        '모델',
        '생성 시각',
        '담당자',
        '기한',
        '시각',
        '시각'],
 'pt': ['Resumo da reunião',
        'Temas',
        'Decisões',
        'Tarefas',
        'Riscos',
        'Questões em aberto',
        'Nenhum item registrado.',
        'Sem título',
        'Perfil',
        'Modelo',
        'Gerado',
        'Responsável',
        'Prazo',
        'Horário',
        'Horários'],
 'zh-Hant': ['會議摘要',
             '主題',
             '決定',
             '待辦事項',
             '風險',
             '待解決問題',
             '未記錄任何內容。',
             '無標題',
             '模式',
             '模型',
             '產生時間',
             '負責人',
             '截止日期',
             '時間戳',
             '時間戳'],
 'pa-Arab': ['میٹنگ دا خلاصہ',
             'موضوع',
             'فیصلے',
             'کم',
             'خطرے',
             'کھلے سوال',
             'کوئی معلومات درج نہیں کیتیاں گئیاں۔',
             'بغیر عنوان',
             'پروفائل',
             'ماڈل',
             'تیار کیتا',
             'ذمہ وار',
             'آخری تاریخ',
             'ویلا',
             'ویلے']}

PROFILE_LABELS = {
    "en": ("Concise", "Balanced", "Detailed", "Action items"),
    "es": ("Conciso", "Equilibrado", "Detallado", "Tareas"),
    "fr": ("Concis", "Équilibré", "Détaillé", "Actions"),
    "de": ("Kurz", "Ausgewogen", "Ausführlich", "Aufgaben"),
    "zh": ("简洁", "均衡", "详细", "待办事项"),
    "zh-Hant": ("簡潔", "均衡", "詳細", "待辦事項"),
    "ja": ("簡潔", "標準", "詳細", "作業項目"),
    "it": ("Conciso", "Equilibrato", "Dettagliato", "Attività"),
    "pa": ("ਸੰਖੇਪ", "ਸੰਤੁਲਿਤ", "ਵਿਸਥਾਰਪੂਰਵਕ", "ਕੰਮ"),
    "pa-Arab": ("مختصر", "متوازن", "تفصیلی", "کم"),
    "hi": ("संक्षिप्त", "संतुलित", "विस्तृत", "कार्य"),
    "ko": ("간결", "균형", "상세", "작업 항목"),
    "pt": ("Conciso", "Equilibrado", "Detalhado", "Tarefas"),
}
